# Generated by Django 3.2.7 on 2021-09-10 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preguntas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termino', models.BooleanField(default=False)),
                ('dificultad', models.CharField(choices=[('1', 'Fácil'), ('2', 'Media'), ('3', 'Difícil')], default='1', max_length=1)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('preguntas', models.ManyToManyField(related_name='PreguntasDeLaPartida', to='preguntas.Pregunta')),
            ],
        ),
    ]
