# Generated by Django 3.2.7 on 2021-09-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='puntaje',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
